# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          DOCKER_TAG=${{ github.ref_name }}
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            DOCKER_TAG=${{ github.ref_name }}
            docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} .
            docker push ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}
            docker tag ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} ${DOCKER_IMAGE_NAME}:latest
            docker push ${DOCKER_IMAGE_NAME}:latest
          else
            DOCKER_TAG=${{ github.sha }}
            docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} .
            docker push ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}
          fi

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
